### ISSUE TITLE
IMPORTANT: Documentation roadmap

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#298]
It has become very high priority to introduce documentation to Foley. There's a few features e.g. SVG Sprite which I know how to make work in my head but correct settings and rules haven't been written down which means the barrier to entry is too high. 

As the core of Foley is pretty much set in stone for now, this is the right time to start documentation.

The documentation should be automatically published to a website but be kept in the master branch alongside the workflow.

This ticket will be updated with tasks and documentation sections in the future.

Technical Roadmap:
- [ ] Investigate Gitbooks
- [ ] Investigate Sphinx (I did a POC for this a while ago)
- [ ] Investigate GitHub Wiki
- [ ] Can Travis CI publish the documentation?
- [ ] More TBA

Content Roadmap:
- [ ] TBA

**Comment by furzeface** [comment]
GitHub wiki?

**Comment by phildotdev** [comment]
@furzeface thats a good suggestion but I don't like how the wiki is separated from the repo. Ideally I'd like the documentation files to be included for offline usage.
